/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GuiChatApp;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.PrintWriter;
import java.net.Socket;
import java.util.HashSet;
import java.util.Set;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;

/**
 *
 * @author Fauzi
 */
public class Client extends javax.swing.JFrame {

    /**
     * Creates new form Gui
     */
    private Set<String> activeUsernames = new HashSet<>();
    private Socket socket;
    private PrintWriter out;
    private BufferedReader in;
//    
    public Client() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        username = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        semuaPesan = new javax.swing.JTextArea();
        pesanClient = new javax.swing.JTextField();
        tombolKirim = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });

        jLabel1.setText("Username");

        semuaPesan.setEditable(false);
        semuaPesan.setColumns(20);
        semuaPesan.setRows(5);
        jScrollPane1.setViewportView(semuaPesan);

        pesanClient.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                pesanClientKeyReleased(evt);
            }
        });

        tombolKirim.setText("Kirim");
        tombolKirim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolKirimActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(username))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pesanClient, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tombolKirim, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tombolKirim, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
                    .addComponent(pesanClient))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        String enteredUsername = username.getText();

        if (isUsernameAvailable(enteredUsername)) {
            // Username is available. Add it to the list of active usernames.
            activeUsernames.add(enteredUsername);
        } else {
            // Username is already in use. Inform the user and prompt for a different username.
            JOptionPane.showMessageDialog(this, "Username is already in use. Please choose a different username.");
            username.setText(""); // Clear the input field or allow the user to choose another username.
        }
    }//GEN-LAST:event_usernameActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
          try {
            socket = new Socket("localhost", 12345);
            out = new PrintWriter(socket.getOutputStream(), true);
            in = new BufferedReader(new InputStreamReader(socket.getInputStream()));

            new PesanServer(in,semuaPesan).start();

        } catch (IOException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_formWindowOpened

    private boolean isUsernameAvailable(String enteredUsername) {
        return !activeUsernames.contains(username.getText());
    }

    public static class PesanServer extends Thread {
        private BufferedReader in;
        private JTextArea text;
        public PesanServer(BufferedReader in,JTextArea text) {
            this.in = in;
            this.text = text;
        }

        @Override
        public void run() {
            try {
                String message;
                while ((message = in.readLine()) != null) {
                    // Append the received message to the GUI's JTextArea.
                    text.append(message + "\n");
                }
            } catch (IOException e) {
                e.printStackTrace();
            }
        }
    }
    private static String encryptMessage(String message) {
        String temp = "";
            int key = 15;
            for (int i = 0; i < message.length(); i++) {
                int h = (int) (message.charAt(i));
                char t = (char) (h^key);
                temp += t;
            }
            return temp;
    }
    
    private void tombolKirimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolKirimActionPerformed
        String username = this.username.getText();
        String message = pesanClient.getText();
        String encryptedMessage = encryptMessage(username + " : " + message);
        out.println(encryptedMessage);
        pesanClient.setText("");
    }//GEN-LAST:event_tombolKirimActionPerformed

    private void pesanClientKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pesanClientKeyReleased
         if (evt.getKeyCode() == evt.VK_ENTER) {
        // Check if the Enter key is released
        String username = this.username.getText();
        String message = pesanClient.getText();
        String encryptedMessage = encryptMessage(username + " : " + message);
        out.println(encryptedMessage);
        pesanClient.setText("");
    }
    }//GEN-LAST:event_pesanClientKeyReleased

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Client.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new Client().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField pesanClient;
    private javax.swing.JTextArea semuaPesan;
    private javax.swing.JButton tombolKirim;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
